DROP TABLE IF EXISTS FINES;
DROP TABLE IF EXISTS BOOK_LOANS;
DROP TABLE IF EXISTS BOOK_AUTHORS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BORROWER;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    Isbn VARCHAR(20) PRIMARY KEY,
    Title VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORS (
    Author_id INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE BOOK_AUTHORS (
    Isbn VARCHAR(20),
    Author_id INT,
    PRIMARY KEY (Isbn, Author_id),
    FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
    FOREIGN KEY (Author_id) REFERENCES AUTHORS(Author_id)
);

CREATE TABLE BORROWER (
    Card_id VARCHAR(10) PRIMARY KEY,
    Bname VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Ssn VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE BOOK_LOANS (
    Loan_id INT AUTO_INCREMENT PRIMARY KEY,
    Isbn VARCHAR(20),
    Card_id VARCHAR(10),
    Date_out DATE,
    Due_date DATE,
    Date_in DATE,
    FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
    FOREIGN KEY (Card_id) REFERENCES BORROWER(Card_id)
);

CREATE TABLE FINES (
    Loan_id INT PRIMARY KEY,
    Fine_amt DECIMAL(10,2),
    Paid BOOLEAN,
    FOREIGN KEY (Loan_id) REFERENCES BOOK_LOANS(Loan_id)
);
