DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOK_AUTHORS;
DROP TABLE IF EXISTS BORROWER;
DROP TABLE IF EXISTS BOOK_LOANS;
DROP TABLE IF EXISTS FINES;

CREATE TABLE BOOK (
    Isbn TEXT PRIMARY KEY,
    Title TEXT NOT NULL
);

CREATE TABLE AUTHORS (
    Author_id INTEGER PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE BOOK_AUTHORS (
    Isbn TEXT,
    Author_id INTEGER,
    PRIMARY KEY (Isbn, Author_id),
    FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
    FOREIGN KEY (Author_id) REFERENCES AUTHORS(Author_id)
);

CREATE TABLE BORROWER (
    Card_id TEXT PRIMARY KEY,
    Bname TEXT NOT NULL,
    Address TEXT NOT NULL,
    Phone TEXT NOT NULL,
    Ssn TEXT NOT NULL UNIQUE
);

CREATE TABLE BOOK_LOANS (
    Loan_id INTEGER PRIMARY KEY AUTOINCREMENT,
    Isbn TEXT,
    Card_id TEXT,
    Date_out DATE,
    Due_date DATE,
    Date_in DATE,
    FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
    FOREIGN KEY (Card_id) REFERENCES BORROWER(Card_id)
);

CREATE TABLE FINES (
    Loan_id INTEGER PRIMARY KEY,
    Fine_amt DECIMAL(10, 2),
    Paid INTEGER CHECK (Paid IN (0, 1)),
    FOREIGN KEY (Loan_id) REFERENCES BOOK_LOANS(Loan_id)
);
