# Generated by Django 5.2 on 2025-05-04 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)])),
                ('title', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='books', to='libraryapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookloan')),
            ],
        ),
    ]
